name: sil-kil-ci/upload-artifacts

description: Upload artifacts created in the CI run.

inputs:

  upload-artifacts:
    description: Determines if artifacts created by the actions should be uploaded
    required: true

  retention-days:
    description: Determines the number of days any uploaded artifacts should be retained
    required: true

  package-name:
    description: Name of the package to upload as an artifact
    required: true

  package-path:
    description: Path of the package to upload as an artifact
    required: true

runs:
  using: composite
  steps:

    - name: (all) upload package as artifact
      if: ${{ inputs.upload-artifacts == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.package-name }}
        path: ${{ inputs.package-path }}
        retention-days: ${{ inputs.retention-days }}
        if-no-files-found: 'error'
