name: sil-kil-ci/cmake-build

description: Build the project with CMake.

inputs:

  preset-name:
    description: The preset name from CMakePresets.json.
    required: true

  linux-docker-image:
    default: ghcr.io/mariusbgm/sil-kit-ci-ubuntu-22.04:main
    description: Docker image used under Linux
    required: false

  cmake-source-directory:
    description: The source directory for use by the cmake actions
    required: true

  cmake-build-directory:
    description: The build directory for use by the cmake actions
    required: true

  cmake-package-directory:
    description: The package directory for use by the cmake actions
    required: true

runs:
  using: composite
  steps:

    - name: (linux) build cmake project
      if: runner.os == 'Linux'
      shell: bash
      run: |
        docker run \
          -v "${{ inputs.cmake-source-directory }}:/s" \
          -v "${{ inputs.cmake-build-directory }}:/b" \
          -v "${{ inputs.cmake-package-directory }}:/p" \
          -e "SIL_KIT_CI_CMAKE_BINARY_DIR=/b" \
          -e "SIL_KIT_CI_CMAKE_INSTALL_DIR=/b/i" \
          -w "/s" \
          "${{ inputs.linux-docker-image }}" \
            cmake \
              --build \
              --preset "${{ inputs.preset-name }}" \
              --parallel

    - name: (windows) build cmake project
      if: runner.os == 'Windows'
      shell: powershell
      env:
        SIL_KIT_CI_CMAKE_BINARY_DIR: "${{ inputs.cmake-build-directory }}"
        SIL_KIT_CI_CMAKE_INSTALL_DIR: "${{ inputs.cmake-build-directory }}/i"
      working-directory: ${{ inputs.cmake-source-directory }}
      run: |
        cmake `
          --build `
          --preset "${{ inputs.preset-name }}" `
          --parallel
