name: sil-kil-ci/cmake-configure

description: Configure the project with CMake.

inputs:

  preset-name:
    description: The preset name from CMakePresets.json.
    required: true

  linux-docker-image:
    default: ghcr.io/mariusbgm/sil-kit-ci-ubuntu-22.04:main
    description: Docker image used under Linux
    required: false

  cmake-source-directory:
    description: The source directory for use by the cmake actions
    required: true

  cmake-build-directory:
    description: The build directory for use by the cmake actions
    required: true

  cmake-package-directory:
    description: The package directory for use by the cmake actions
    required: true

runs:
  using: composite
  steps:

    - name: (all) configure cmake project
      uses: ./.github/actions/sil-kit-ci/execute-command
      with:
        linux-docker-image: ${{ inputs.linux-docker-image }}
        msvc-arch: ${{ inputs.msvc-arch }}
        msvc-toolset: ${{ inputs.msvc-toolset }}
        cmake-source-directory: ${{ inputs.cmake-source-directory }}
        cmake-build-directory: ${{ inputs.cmake-build-directory }}
        cmake-package-directory: ${{ inputs.cmake-package-directory }}
        command: cmake
        args: --preset "${{ inputs.preset-name }}"
