name: sil-kil-ci/cmake-configure

description: Configure the project with CMake.

inputs:

  preset-name:
    description: The preset name from CMakePresets.json.
    required: true

  linux-docker-image:
    default: ghcr.io/mariusbgm/sil-kit-ci-ubuntu-22.04:main
    description: Docker image used under Linux
    required: false

  cmake-source-directory:
    description: The source directory for use by the cmake actions
    required: true

  cmake-build-directory:
    description: The build directory for use by the cmake actions
    required: true

  cmake-package-directory:
    description: The package directory for use by the cmake actions
    required: true

runs:
  using: composite
  steps:

    - name: (linux) configure cmake project
      if: runner.os == 'Linux'
      shell: bash
      run: |
        docker run \
          -v "${{ inputs.cmake-source-directory }}:/s" \
          -v "${{ inputs.cmake-build-directory }}:/b" \
          -v "${{ inputs.cmake-package-directory }}:/p" \
          "${{ inputs.linux-docker-image }}" \
            cmake \
              -S /s \
              -B /b \
              -G Ninja \
              -D CMAKE_BUILD_TYPE=Release \
              -D CPACK_PACKAGE_DIRECTORY=/p \
              -D SILKIT_BUILD_DEMOS=OFF \
              -D SILKIT_BUILD_UTILITIES=OFF \
              -D SILKIT_BUILD_DASHBOARD=OFF \
              -D SILKIT_BUILD_DOCS=OFF

    - name: (windows x64) configure cmake project
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        cmake `
          -S "${{ inputs.cmake-source-directory }}" `
          -B "${{ inputs.cmake-build-directory }}" `
          -G Ninja `
          -D CMAKE_BUILD_TYPE=Release `
          -D "CPACK_PACKAGE_DIRECTORY=${{ inputs.cmake-package-directory }}" `
          -D SILKIT_BUILD_DEMOS=OFF `
          -D SILKIT_BUILD_UTILITIES=OFF `
          -D SILKIT_BUILD_DASHBOARD=OFF `
          -D SILKIT_BUILD_DOCS=OFF
