name: sil-kil-ci/execute

description: >
  Execute a command with arguments.
  On Linux runners, the command is executed in a docker container using the `linux-docker-image`.
  On Windows runners, the command is executed on the runner itself.

inputs:

  preset-name:
    description: The preset name from CMakePresets.json.
    required: true

  linux-docker-image:
    description: Docker image used under Linux
    required: true

  command:
    description: Command line to be executed
    required: true

runs:
  using: composite
  steps:

    - name: compute directories
      uses: ./.github/actions/sil-kit-ci/dirs
      id: dirs
      with:
        preset-name: ${{ inputs.preset-name }}

    - name: (linux) execute command
      if: runner.os == 'Linux'
      shell: bash
      run: |
        docker run \
          -v "${{ steps.dirs.outputs.cmake-source }}:/s" \
          -v "${{ steps.dirs.outputs.cmake-build }}:/b" \
          -v "${{ steps.dirs.outputs.cmake-package }}:/p" \
          -e "SIL_KIT_CI_CMAKE_BINARY_DIR=/b" \
          -e "SIL_KIT_CI_CMAKE_INSTALL_DIR=/b/i" \
          -e "SIL_KIT_CI_CMAKE_PACKAGE_DIR=/p" \
          -w "/s" \
          "${{ inputs.linux-docker-image }}" \
            ${{ inputs.command }}

    - name: (windows) execute command
      if: runner.os == 'Windows'
      shell: powershell
      env:
        SIL_KIT_CI_CMAKE_BINARY_DIR: "${{ steps.dirs.outputs.cmake-build }}"
        SIL_KIT_CI_CMAKE_INSTALL_DIR: "${{ steps.dirs.outputs.cmake-build }}/i"
        SIL_KIT_CI_CMAKE_PACKAGE_DIR: "${{ steps.dirs.outputs.cmake-package }}"
      working-directory: ${{ steps.dirs.outputs.cmake-source }}
      run: |
        & ${{ inputs.command }}
