name: sil-kil-ci/cmake-build

description: Package the project with CMake (CTest).

inputs:

  preset-name:
    description: The preset name from CMakePresets.json.
    required: true

  linux-docker-image:
    description: Docker image used under Linux
    required: true

  msvc-arch:
    description: Target architecture used under Windows/MSVC
    required: true

  msvc-toolset:
    description: Target toolset used under Windows/MSVC
    required: true

  cmake-source-directory:
    description: The source directory for use by the cmake actions
    required: true

  cmake-build-directory:
    description: The build directory for use by the cmake actions
    required: true

  cmake-package-directory:
    description: The package directory for use by the cmake actions
    required: true

outputs:

  package-path:
    description: Path to the package
    value: ${{ join(steps.*.outputs.package-path, '') }}

runs:
  using: composite
  steps:

    - name: (linux) package cmake project
      if: runner.os == 'Linux'
      shell: bash
      run: |
        docker run \
          -v "${{ inputs.cmake-source-directory }}:/s" \
          -v "${{ inputs.cmake-build-directory }}:/b" \
          -v "${{ inputs.cmake-package-directory }}:/p" \
          "${{ inputs.linux-docker-image }}" \
            cmake \
              --build /b \
              --target package

        echo "package-path=${{ inputs.cmake-package-directory }}/*/ZIP/SilKit-*-*.zip" >> "$GITHUB_OUTPUT"

    - name: (windows) package cmake project
      if: runner.os == 'Windows'
      shell: powershell
      run: |
        cmake `
          --build "${{ inputs.cmake-build-directory }}" `
          --target package

        echo "package-path=${{ inputs.cmake-package-directory }}/*/ZIP/SilKit-*-*.zip" >> "$env:GITHUB_OUTPUT"
