name: sil-kil-ci/cmake-build

description: Package the project with CMake (CTest).

inputs:

  preset-name:
    description: The preset name from CMakePresets.json.
    required: true

  linux-docker-image:
    description: Docker image used under Linux
    required: true

  msvc-arch:
    description: Target architecture used under Windows/MSVC
    required: true

  msvc-toolset:
    description: Target toolset used under Windows/MSVC
    required: true

  cmake-source-directory:
    description: The source directory for use by the cmake actions
    required: true

  cmake-build-directory:
    description: The build directory for use by the cmake actions
    required: true

  cmake-package-directory:
    description: The package directory for use by the cmake actions
    required: true

outputs:

  package-path:
    description: Path to the package
    value: ${{ join(steps.*.outputs.package-path, '') }}

runs:
  using: composite
  steps:

    - name: (all) build cmake project
      uses: ./.github/actions/sil-kit-ci/execute-command
      with:
        linux-docker-image: ${{ inputs.linux-docker-image }}
        msvc-arch: ${{ inputs.msvc-arch }}
        msvc-toolset: ${{ inputs.msvc-toolset }}
        cmake-source-directory: ${{ steps.dirs.outputs.cmake-source }}
        cmake-build-directory: ${{ steps.dirs.outputs.cmake-build }}
        cmake-package-directory: ${{ steps.dirs.outputs.cmake-package }}
        command: cmake
        args: --build --preset "${{ inputs.preset-name }}" --target package

    - name: (linux, windows) compute outputs
      id: compute-outputs
      if: runner.os == 'Linux' || runner.os == 'Windows'
      shell: bash
      run: |
        echo 'package-path=${{ inputs.cmake-package-directory }}/SilKit-*-*.zip' >> "$GITHUB_OUTPUT"
