name: sil-kil-ci/cmake-build

description: Package the project with CMake (CTest).

inputs:

  preset-name:
    description: The preset name from CMakePresets.json.
    required: true

  linux-docker-image:
    default: ghcr.io/mariusbgm/sil-kit-ci-ubuntu-22.04:main
    description: Docker image used under Linux
    required: false

  cmake-source-directory:
    description: The source directory for use by the cmake actions
    required: true

  cmake-build-directory:
    description: The build directory for use by the cmake actions
    required: true

  cmake-package-directory:
    description: The package directory for use by the cmake actions
    required: true

runs:
  using: composite
  steps:

    - name: (linux) package cmake project
      if: runner.os == 'Linux'
      shell: bash
      run: |
        docker run \
          -v "${{ inputs.cmake-source-directory }}:/s" \
          -v "${{ inputs.cmake-build-directory }}:/b" \
          -v "${{ inputs.cmake-package-directory }}:/p" \
          "${{ inputs.linux-docker-image }}" \
            cmake \
              --build /b \
              --target package
