name: sil-kil-ci/cmake-package

description: Package the project with CMake (CPack).

inputs:

  preset-name:
    description: The preset name from CMakePresets.json.
    required: true

  linux-docker-image:
    description: Docker image used under Linux
    required: true

outputs:

  package-path:
    description: Path to the package
    value: ${{ join(steps.*.outputs.package-path, '') }}

runs:
  using: composite
  steps:

    - name: compute directories
      uses: ./.github/actions/sil-kit-ci/dirs
      id: dirs
      with:
        preset-name: ${{ inputs.preset-name }}

    - name: (all) build cmake project
      uses: ./.github/actions/sil-kit-ci/execute
      with:
        preset-name: ${{ inputs.preset-name }}
        linux-docker-image: ${{ inputs.linux-docker-image }}
        command: cmake
        args: --build --preset "${{ inputs.preset-name }}" --target package

    - name: (linux, windows) compute outputs
      id: compute-outputs
      if: runner.os == 'Linux' || runner.os == 'Windows'
      shell: bash
      run: |
        echo 'package-path=${{ steps.dirs.outputs.cmake-package }}/SilKit-*-*.zip' >> "$GITHUB_OUTPUT"
