name: sil-kil-ci/cmake-build

description: Package the project with CMake (CTest).

inputs:

  preset-name:
    description: The preset name from CMakePresets.json.
    required: true

  linux-docker-image:
    description: Docker image used under Linux
    required: true

  msvc-arch:
    description: Target architecture used under Windows/MSVC
    required: true

  msvc-toolset:
    description: Target toolset used under Windows/MSVC
    required: true

  cmake-source-directory:
    description: The source directory for use by the cmake actions
    required: true

  cmake-build-directory:
    description: The build directory for use by the cmake actions
    required: true

  cmake-package-directory:
    description: The package directory for use by the cmake actions
    required: true

outputs:

  package-path:
    description: Path to the package
    value: ${{ join(steps.*.outputs.package-path, '') }}

runs:
  using: composite
  steps:

    - name: (linux) package cmake project
      id: cmake-package-linux
      if: runner.os == 'Linux'
      shell: bash
      run: |
        docker run \
          -v "${{ inputs.cmake-source-directory }}:/s" \
          -v "${{ inputs.cmake-build-directory }}:/b" \
          -v "${{ inputs.cmake-package-directory }}:/p" \
          -e "SIL_KIT_CI_CMAKE_BINARY_DIR=/b" \
          -e "SIL_KIT_CI_CMAKE_INSTALL_DIR=/b/i" \
          -w "/s" \
          "${{ inputs.linux-docker-image }}" \
            cmake \
              --build \
              --preset "${{ inputs.preset-name }}" \
              --target package

        echo 'package
        echo 'package-path=${{ inputs.cmake-package-directory }}/*/ZIP/SilKit-*-*.zip' >> "$GITHUB_OUTPUT"

    - name: (windows) package cmake project
      id: cmake-package-windows
      if: runner.os == 'Windows'
      shell: powershell
      working-directory: ${{ inputs.cmake-source-directory }}
      env:
        SIL_KIT_CI_CMAKE_BINARY_DIR: "${{ inputs.cmake-build-directory }}"
        SIL_KIT_CI_CMAKE_INSTALL_DIR: "${{ inputs.cmake-build-directory }}/i"
      run: |
        cmake `
          --build `
          --preset "${{ inputs.preset-name }}" `
          --target package
