name: sil-kit-ci/setup

description: Setup the environment for the other CI actions.

inputs:

  linux-docker-image:
    default: ghcr.io/mariusbgm/sil-kit-ci-ubuntu-22.04:main
    description: Docker image used under Linux
    required: false

  cmake-source-directory:
    description: The source directory for use by the cmake actions
    required: true

  cmake-build-directory:
    description: The build directory for use by the cmake actions
    required: true

  cmake-package-directory:
    description: The package directory for use by the cmake actions
    required: true

runs:
  using: composite
  steps:

    - name: (all) checkout sil-kit sources
      uses: actions/checkout@v4
      with:
        path: ${{ inputs.cmake-source-directory }}
        submodules: true

    - name: (linux) cleanup build and package directories
      if: runner.os == 'Linux'
      shell: bash
      run: |
        rm -rf \
          "${{ inputs.cmake-build-directory }}" \
          "${{ inputs.cmake-package-directory }}"

    - name: (linux) create build and package directories
      if: runner.os == 'Linux'
      shell: bash
      run: |
        mkdir -p \
          "${{ inputs.cmake-build-directory }}" \
          "${{ inputs.cmake-package-directory }}"

    - name: (linux) pull docker image for building via cmake
      if: runner.os == 'Linux'
      shell: bash
      run: docker pull "${{ inputs.linux-docker-image }}"
