name: sil-kit-ci/run

description: Run the SIL Kit CI builds.

inputs:

  preset-name:
    description: The preset name from CMakePresets.json
    required: true

  linux-docker-image:
    description: Docker image used under Linux
    required: false
    default: ghcr.io/mariusbgm/sil-kit-ci-ubuntu-22.04:main

  msvc-arch:
    description: Target architecture used under Windows/MSVC
    required: false
    default: 'x64'

  msvc-toolset:
    description: Target toolset used under Windows/MSVC
    required: false
    default: '14.1'

  upload-artifacts:
    description: Determines if artifacts created by the actions should be uploaded
    required: false
    default: 'false'

  retention-days:
    description: Determines the number of days any uploaded artifacts should be retained
    required: false
    default: '1'

  package-name:
    description: Name of the package to upload as an artifact
    required: false
    default: 'sil-kit.zip'

runs:
  using: composite
  steps:

    - name: compute directories
      uses: ./.github/actions/sil-kit-ci/dirs
      id: dirs
      with:
        preset-name: ${{ inputs.preset-name }}

    - name: setup
      uses: ./.github/actions/sil-kit-ci/setup
      id: setup
      with:
        linux-docker-image: ${{ inputs.linux-docker-image }}
        cmake-source-directory: ${{ steps.dirs.outputs.cmake-source }}
        cmake-build-directory: ${{ steps.dirs.outputs.cmake-build }}
        cmake-package-directory: ${{ steps.dirs.outputs.cmake-package }}

    - name: cmake configure
      uses: ./.github/actions/sil-kit-ci/cmake-configure
      id: cmake-configure
      with:
        preset-name: ${{ inputs.preset-name }}
        linux-docker-image: ${{ inputs.linux-docker-image }}
        cmake-source-directory: ${{ steps.dirs.outputs.cmake-source }}
        cmake-build-directory: ${{ steps.dirs.outputs.cmake-build }}
        cmake-package-directory: ${{ steps.dirs.outputs.cmake-package }}

    - name: cmake build
      uses: ./.github/actions/sil-kit-ci/cmake-build
      id: cmake-build
      with:
        preset-name: ${{ inputs.preset-name }}
        linux-docker-image: ${{ inputs.linux-docker-image }}
        cmake-source-directory: ${{ steps.dirs.outputs.cmake-source }}
        cmake-build-directory: ${{ steps.dirs.outputs.cmake-build }}
        cmake-package-directory: ${{ steps.dirs.outputs.cmake-package }}

    - name: cmake test
      uses: ./.github/actions/sil-kit-ci/cmake-test
      id: cmake-test
      with:
        preset-name: ${{ inputs.preset-name }}
        linux-docker-image: ${{ inputs.linux-docker-image }}
        cmake-source-directory: ${{ steps.dirs.outputs.cmake-source }}
        cmake-build-directory: ${{ steps.dirs.outputs.cmake-build }}
        cmake-package-directory: ${{ steps.dirs.outputs.cmake-package }}

    - name: cmake package
      uses: ./.github/actions/sil-kit-ci/cmake-package
      id: cmake-package
      with:
        preset-name: ${{ inputs.preset-name }}
        linux-docker-image: ${{ inputs.linux-docker-image }}
        cmake-source-directory: ${{ steps.dirs.outputs.cmake-source }}
        cmake-build-directory: ${{ steps.dirs.outputs.cmake-build }}
        cmake-package-directory: ${{ steps.dirs.outputs.cmake-package }}

    - name: upload-artifacts
      uses: ./.github/actions/sil-kit-ci/upload-artifacts
      id: upload-artifacts
      with:
        preset-name: ${{ inputs.preset-name }}
        upload-artifacts: ${{ inputs.upload-artifacts }}
        retention-days: ${{ inputs.retention-days }}
        package-name: ${{ inputs.package-name }}
        package-path: ${{ steps.cmake-package.outputs.package-path }}
