name: sil-kit-ci/run

description: Run the SIL Kit CI builds.

inputs:

  preset-name:
    description: The preset name from CMakePresets.json
    required: true

  linux-docker-image:
    description: Docker image used under Linux
    required: true

  linux-c-compiler:
    description: C compiler used under Linux
    required: true

  linux-cxx-compiler:
    description: C++ compiler used under Linux
    required: true

  msvc-arch:
    description: Target architecture used under Windows/MSVC
    required: true

  msvc-toolset:
    description: Target toolset used under Windows/MSVC
    required: true

  upload-artifacts:
    description: Determines if artifacts created by the actions should be uploaded
    required: true

  retention-days:
    description: Determines the number of days any uploaded artifacts should be retained
    required: true

  package-name:
    description: Name of the package to upload as an artifact
    required: true

  cmake-configure-args:
    description: Extra arguments passed to cmake during configuration
    required: true

  cmake-build-args:
    description: Extra arguments passed to cmake during building
    required: true

  ctest-args:
    description: Extra arguments passed to ctest
    required: true

  cmake-package-args:
    description: Extra arguments passed to cmake during packaging
    required: true

runs:
  using: composite
  steps:

    - name: setup
      uses: ./.github/actions/sil-kit-ci/setup
      id: setup
      with:
        preset-name: ${{ inputs.preset-name }}
        linux-docker-image: ${{ inputs.linux-docker-image }}
        linux-c-compiler: ${{ inputs.linux-c-compiler }}
        linux-cxx-compiler: ${{ inputs.linux-cxx-compiler }}
        msvc-arch: ${{ inputs.msvc-arch }}
        msvc-toolset: ${{ inputs.msvc-toolset }}

    - name: configure cmake project
      uses: ./.github/actions/sil-kit-ci/execute
      with:
        preset-name: ${{ inputs.preset-name }}
        linux-docker-image: ${{ inputs.linux-docker-image }}
        command: cmake --preset "${{ inputs.preset-name }}" ${{ steps.setup.outputs.cmake-configure-args }} ${{ inputs.cmake-configure-args }}

    - name: build cmake project
      uses: ./.github/actions/sil-kit-ci/execute
      with:
        preset-name: ${{ inputs.preset-name }}
        linux-docker-image: ${{ inputs.linux-docker-image }}
        command: cmake --build --preset "${{ inputs.preset-name }}" --parallel ${{ inputs.cmake-build-args }}

    - name: test cmake project
      uses: ./.github/actions/sil-kit-ci/execute
      with:
        preset-name: ${{ inputs.preset-name }}
        linux-docker-image: ${{ inputs.linux-docker-image }}
        command: ctest --preset "${{ inputs.preset-name }}" ${{ inputs.ctest-args }}

    - name: package cmake project
      uses: ./.github/actions/sil-kit-ci/cmake-package
      id: cmake-package
      with:
        preset-name: ${{ inputs.preset-name }}
        linux-docker-image: ${{ inputs.linux-docker-image }} ${{ inputs.cmake-package-args }}

    - name: upload-artifacts
      uses: ./.github/actions/sil-kit-ci/upload-artifacts
      id: upload-artifacts
      with:
        upload-artifacts: ${{ inputs.upload-artifacts }}
        retention-days: ${{ inputs.retention-days }}
        package-name: ${{ inputs.package-name }}
        package-path: ${{ steps.cmake-package.outputs.package-path }}
