name: "CI for Pull Requests"

on:

  pull_request:
    branches: [ 'main' ]

concurrency:

  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:

  linux-fast:
    name: 'Linux (PR)'
    uses: ./.github/workflows/call-build.yml
    with:
      runs-on: ubuntu-22.04
      preset-name: ci
      c-compiler: gcc-8
      cxx-compiler: g++-8
      cmake-configure-args: >-
        -D CMAKE_C_FLAGS_RELEASE="-g0 -O0"
        -D CMAKE_CXX_FLAGS_RELEASE="-g0 -O0"

  windows-x64-fast:
    name: 'Windows (PR, x64)'
    uses: ./.github/workflows/call-build.yml
    with:
      runs-on: windows-2019
      preset-name: ci
      msvc-arch: x64
      msvc-toolset: 14.1
      cmake-configure-args: >-
        -D CMAKE_C_FLAGS_RELEASE="/Od"
        -D CMAKE_CXX_FLAGS_RELEASE="/Od"
