name: 'Build Packages'

on:
  workflow_call:
    inputs:
      retention-days:
        required: false
        type: number
        default: 14
      run:
        required: true
        type: boolean

jobs:

  run:
    name: Linux
    environment: public-github-runners
    runs-on: ubuntu-22.04
    if: inputs.run == true

    steps:

      - name: checkout sil-kit workflows and actions
        uses: actions/checkout@v4
        with:
          submodules: false
          sparse-checkout: .github

      - name: run ci build
        uses: ./.github/actions/sil-kit-ci/run
        with:
          preset-name: ci-linux
          upload-artifacts: true
          retention-days: 1
          package-name: silkit-linux

  build-windows-x86:
    name: Windows (x86)
    environment: public-github-runners
    runs-on: windows-2019
    if: inputs.run == true

    steps:

      - name: checkout sil-kit workflows and actions
        uses: actions/checkout@v4
        with:
          submodules: false
          sparse-checkout: .github

      - name: run ci build
        uses: ./.github/actions/sil-kit-ci/run
        with:
          preset-name: ci-windows
          msvc-arch: x86
          msvc-toolset: 14.1
          upload-artifacts: true
          retention-days: 1
          package-name: silkit-windows-x86

  build-windows-x64:
    name: Windows (x64)
    environment: public-github-runners
    runs-on: windows-2019
    if: inputs.run == true

    steps:

      - name: checkout sil-kit workflows and actions
        uses: actions/checkout@v4
        with:
          submodules: false
          sparse-checkout: .github

      - name: run ci build
        uses: ./.github/actions/sil-kit-ci/run
        with:
          preset-name: ci-windows
          msvc-arch: x64
          msvc-toolset: 14.1
          upload-artifacts: true
          retention-days: 1
          package-name: silkit-windows-x64
