name: 'Build Packages'

on:
  workflow_call:
    inputs:

      upload-artifacts:
        required: false
        type: boolean
        default: false

      retention-days:
        required: false
        type: number
        default: 1

      run:
        required: true
        type: boolean

jobs:

  build-linux:
    name: Linux
    uses: ./.github/workflows/sil-kit-ci-manual-build-package.yml
    if: inputs.run == true
    with:
      runs-on: ubuntu-22.04
      preset-name: ci-linux
      upload-artifacts: ${{ inputs.upload-artifacts }}
      retention-days: ${{ inputs.retention-days }}
      package-name: SilKit-Linux
      extra: |
        {
          "linux": {
            "docker": { "image": "ghcr.io/mariusbgm/sil-kit-ci-ubuntu-18.04:main" },
            "c": { "compiler": "gcc-8" },
            "c++": { "compiler": "g++-8" }
          }
        }

  build-windows-x86:
    name: Windows (x86)
    uses: ./.github/workflows/sil-kit-ci-manual-build-package.yml
    if: inputs.run == true
    with:
      runs-on: windows-2019
      preset-name: ci-windows
      upload-artifacts: ${{ inputs.upload-artifacts }}
      retention-days: ${{ inputs.retention-days }}
      package-name: SilKit-Windows-x86
      extra: |
        {
          "msvc": {
            "arch": "x86",
            "toolset": "14.1"
          }
        }

  build-windows-x64:
    name: Windows (x64)
    uses: ./.github/workflows/sil-kit-ci-manual-build-package.yml
    if: inputs.run == true
    with:
      runs-on: windows-2019
      preset-name: ci-windows
      upload-artifacts: ${{ inputs.upload-artifacts }}
      retention-days: ${{ inputs.retention-days }}
      package-name: SilKit-Windows-x86
      extra: |
        {
          "msvc": {
            "arch": "x86",
            "toolset": "14.1"
          }
        }
